---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Установка вектора
      ansible.builtin.apt:
        deb: https://packages.timber.io/vector/0.33.0/vector_0.33.0-1_amd64.deb
        state: present

    - name: Применение конфига из шаблона
      ansible.builtin.template:
        src: ~/ansible-hw/03/playbook/roles/vector/templates/vector.toml.j2
        dest: /etc/vector/vector.toml
        owner: root
        group: root
        mode: '0644'

    - name: Перезапуск vector вручную (если без systemd)
      ansible.builtin.shell: |
        pkill vector || true
        nohup /usr/bin/vector --config /etc/vector/vector.toml &
      args:
        executable: /bin/bash
      changed_when: false