---
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/library/ubuntu:24.04
    pre_build_image: true
post_build:
  - name: Install Python
    ansible.builtin.apt:
      name:
        - python3
        - python3-pip
      state: present
      update_cache: yes

provisioner:
  name: ansible

verifier:
  name: ansible